---
- name: GEARMAN SERVER ROLE | Install list of gearmand server nessesary packages
  apt: name={{item}}
  with_items:
    - gcc
    - g++
    - libboost-dev
    - libboost-program-options-dev
    - libboost-all-dev
    - libevent-dev
    - cloog-ppl
    - gperf
    - uuid-dev
    - libgearman-dev

- unarchive:
   src: "{{ gearmand_tarball_url }}"
   dest: "{{ default_download_directory }}"
   remote_src: true

- name: GEARMAN SERVER ROLE | Install
  command: "chdir={{ default_download_directory }}/{{ gearmand_tarball_directory }} {{ item }}"
  with_items:
   - ./configure
   - make
   - make install
   - ldconfig

- template:
    src: ../templates/etc/init.d/gearmand.j2
    dest: /etc/init.d/gearmand
    mode: "u=rwx,go=rx"

- name: GEARMAN SERVER ROLE | Update script list
  command: update-rc.d -f gearmand defaults

- name: GEARMAN SERVER ROLE | Ensure gearmand is restarted
  action: service name=gearmand state=restarted
